export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const HANDLE_QUANTITY = 'HANDLE_QUANTITY';
export const TOGGLE_CART = 'TOGGLE_CART';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const IS_PURCHASE_DONE = 'IS_PURCHASE_DONE';
